### ISSUE TITLE
Add to Taginfo Projects

### ISSUE THREAD

**Issue by danieldegroot2** [pnorman/spirit#29]
Show the OpenStreetMap community what [data](https://wiki.openstreetmap.org/wiki/Tags) you are using. Add your project to the [list](https://taginfo.openstreetmap.org/projects) of [Taginfo Projects](https://github.com/taginfo/taginfo-projects).

**Comment by pnorman** [comment]
You could do this by using themepark's ability to emit taginfo files. Should I assign this to you?

**Comment by danieldegroot2** [comment]
Hey Paul,

Thanks for the reply. No, I don't do any coding, so it's free to take.

**Comment by pnorman** [comment]
Closing as unplanned at this time.
